//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayrollSystem.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Employee.
        /// </summary>
        public static string AddEmployeePageTitle {
            get {
                return ResourceManager.GetString("AddEmployeePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Position.
        /// </summary>
        public static string AddPositionPageTitle {
            get {
                return ResourceManager.GetString("AddPositionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Salary Adjustment.
        /// </summary>
        public static string AddSalaryAdjustmentPageTitle {
            get {
                return ResourceManager.GetString("AddSalaryAdjustmentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll System.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Payroll Entry.
        /// </summary>
        public static string CreatePayrollEntryPageTitle {
            get {
                return ResourceManager.GetString("CreatePayrollEntryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employee.
        /// </summary>
        public static string EditEmployeePageTitle {
            get {
                return ResourceManager.GetString("EditEmployeePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Position.
        /// </summary>
        public static string EditPositionPageTitle {
            get {
                return ResourceManager.GetString("EditPositionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Salary Adjustment.
        /// </summary>
        public static string EditSalaryAdjustmentPageTitle {
            get {
                return ResourceManager.GetString("EditSalaryAdjustmentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeePageTitle {
            get {
                return ResourceManager.GetString("EmployeePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Reports.
        /// </summary>
        public static string PayrollReportsPageTitle {
            get {
                return ResourceManager.GetString("PayrollReportsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string PositionPageTitle {
            get {
                return ResourceManager.GetString("PositionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Adjustments.
        /// </summary>
        public static string SalaryAdjustmentPageTitle {
            get {
                return ResourceManager.GetString("SalaryAdjustmentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: DELETING AN EMPLOYEE WILL DELETE ALL OF ITS PAYROLL ENTRIES, CONSIDER MODIFYING THE EMPLOYEE&apos;S END EMPLOYMENT IF YOU WANT TO RETAIN THE PAYROLL ENTRIES!
        ///
        ///Are you sure you want to delete the selected employee?.
        /// </summary>
        public static string WarningDeleteEmployeeMessage {
            get {
                return ResourceManager.GetString("WarningDeleteEmployeeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Employees in this Position will be set to &apos;None&apos;. Are you sure you want to delete the selected position? .
        /// </summary>
        public static string WarningDeletePositionMessage {
            get {
                return ResourceManager.GetString("WarningDeletePositionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected Salary Adjustment?.
        /// </summary>
        public static string WarningDeleteSalaryAdjustmentMessage {
            get {
                return ResourceManager.GetString("WarningDeleteSalaryAdjustmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave? Your changes will not be saved..
        /// </summary>
        public static string WarningLeaveMessage {
            get {
                return ResourceManager.GetString("WarningLeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark this employee&apos;s employment leave date today? This will prevent you from creating payroll entries, editing, or deleting this employee..
        /// </summary>
        public static string WarningMarkEmployeeEndEmploymentMessage {
            get {
                return ResourceManager.GetString("WarningMarkEmployeeEndEmploymentMessage", resourceCulture);
            }
        }
    }
}
